# app/domain/policy.py

BASE_FARE = 25
FREE_DISTANCE_KM = 2
PER_KM_RATE = 6

DAILY_INCENTIVE_THRESHOLD = 12
DAILY_INCENTIVE_AMOUNT = 150

RIDER_CANCELLATION_PENALTY = 10

DISPUTE_WINDOW_DAYS = 7

AUTO_PAY_LIMIT = 200